// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbdjsdxncokppesoffru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiZGpzZHhuY29rcHBlc29mZnJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTUzMzksImV4cCI6MjA1OTkzMTMzOX0.EHU2DuDn3HaIc51uSL5oldh6VirT7_zC80GpIKW0JIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);